# This is an example patient file

[conditions]

GI.acetaminophen = 1000.0 # initial dose of 1000 mg

# cofactor availability is 100%
cofactor.UDPGA = 1.0
cofactor.PAPS = 1.0

[solution]
timespan = [ 0.0, 14.0 ] # hours

[physiology]
body_weight = 85.0
cardiac_output = 16.2

# Volumes are given in L/BW^(0.75)
[volumes]
arterial_blood = 0.024
adipose_tissue = 0.21
muscle = 0.4
liver = 0.026
slowly_perfused = 0.19
rapidly_perfused = 0.077
kidneys = 0.0044
venous_blood = 0.056

# Blood flow is given relative to cardiac output. Values will be normalized automatically so they sum to 1.
[flow]
adipose_tissue = 0.052
muscle = 0.1776
liver = 0.2676
slowly_perfused = 0.1276
rapidly_perfused = 0.2076
kidneys = 0.1676

# Absorption rates of oral paracetamol in the gut
[absorption]
TG = 0.332
TP = 0.0476

# Acetaminophen metabolism
[metabolism]

# Metabolism by cytochrome p450 to form NAPQI
[metabolism.cyp]
k_m = 123.0
v_max = 2.57

# Metabolism for the sulfation reaction to obtain APAP-S
[metabolism.sulfation]
k_m = 1.2e3
k_i = 478.0
k_m_cf = 0.345
v_max = 467.0

# Metabolism for the glucuronidation reaction to obtain APAP-G
[metabolism.glucuronidation]
k_m = 6.14e3
k_i = 4.99e4
k_m_cf = 0.343
v_max = 5.21e3

# Reactions involving transport of APAP-S and APAP-G
[transport]

[transport.acetaminophenS]
k_m = 2.23e4
v_max = 1.4e7

[transport.acetaminophenG]
k_m = 1.75e4
v_max = 3.54e4

# Regeneration rates of cofactors
[cofactors]
k_syn_UDPGA = 3.6e4
k_syn_PAPS = 3.66e3

# Kidney clearance rates for molecules
[clearance]
k_renal = 0.0123
k_renal_G = 0.155
k_renal_S = 0.138

# Partition coefficients. Do not edit.
[partition]

[partition.acetaminophen]
adipose_tissue = 0.447
muscle = 0.687
liver = 0.687
slowly_perfused = 0.606
rapidly_perfused = 0.676
kidneys = 0.711

[partition.acetaminophen_G]
adipose_tissue = 0.128
muscle = 0.336
liver = 0.321
slowly_perfused = 0.351
rapidly_perfused = 0.364
kidneys = 0.392

[partition.acetaminophen_S]
adipose_tissue = 0.088
muscle = 0.199
liver = 0.203
slowly_perfused = 0.254
rapidly_perfused = 0.207
kidneys = 0.261

# Metadata. Do not edit.
[meta]

[meta.unit_conversions]
acetaminophen.mg2umol = 6.6155 # micromoles per milligram
